export const strings = {
  agreeByCreate: "Dengan membuat akun baru saya menyetujui",
  alamat: "Alamat Email",
  alert_action: "Batal Langganan",
  alert_action_hapus: "Hapus",
  alert_button: "Gak jadi",
  alert_button_hapus: "Batal",
  alert_text_hapus: "Kamu yakin mau menghapus semua download?",
  alert_text_langganan: "Kamu yakin ingin membatalkan langganan?",
  alertEditProfile: "Kamu hanya  bisa mengubah setiap 6 bulan sekali.",
  ambil_galery: "Ambil dari galeri",
  ambil_langsung: "Ambil langsung",
  audio_Account: "Pengaturan Audio",
  akses_online: "Akses secara offline.",
  akses_penuh: "Akses penuh untuk semua ringkasan buku, tanpa batas!",

  baca: "Baca",
  bahasa: "Pilihan Bahasa",
  beri_ulasan: "Berikan Ulasanmu",
  bookCategory: "Kategori buku",
  bookCollections: "Koleksi buku",
  bookCollectionsDesc:
    "Koleksi sejumlah buku berdasarkan kategori yang kamu minati.",
  booksNotFound: "Kita ga menemukan buku yang kamu cari.",
  btnLewati: "Lewati",
  btnLanjut: "Lanjut",
  button_onBoard_1: "Yuk mulai",
  berlangganan_Account: "Berlangganan",
  btnBatal: "Batal berlangganan",
  btn_batal: "Batal",
  btn_berikan_ulasan: "Berikan Kami Ulasan",
  btn_kebijakan: "Kebijakan Privasi",
  btn_keluar: "Keluar",
  btn_ketentuan: "Ketentuan Layanan",
  btn_simpan: "Simpan",
  buku_serupa: "Buku Serupa",
  best_value: "Best Value",
  bulan: " Bulan",

  camera_unavailable: "Kamera tidak tersedia di perangkat",
  continueReading: "Lanjutkan membaca",
  cacel: "Cancel",

  daftar_isi: "Daftar Isi",
  data_kosong: "Data kosong",
  delete: "Hapus",
  dengar: "Dengar",
  doHaveAcc: "Sudah punya akun?",
  dontHaveAcc: "Belum punya akun?",
  downloadedBooks: "Buku yang diunduh",
  download_Account: "Pengaturan Download",
  dapatkan_ringkasan:
    "Dapatkan semua ringkasan buku dengan upgrade ke premium sekarang!",
  dua_belas_bula: "12 Bulan",
  didepan: " bulan di depan.",

  edit_profile: "Edit Profile",
  emailAddress: "Alamat Email",
  emailCantBeEmpty: "Email tidak boleh kosong",
  emailNotFound: "Email tidak ditemukan",
  emailPlaceholder: "Isi email disini ...",
  emailUsed: "Email sudah terdaftar",
  enterPassword: "Masukin Password",
  enterConfirmPassword: "Konfirmasi Password",
  explore: "Eksplor",

  favBooks: "Buku favoritku",
  findFavBook: "Cari Buku Favoritmu!",
  findFavBookPlaceholder: "Cari buku favoritmu di sini..",
  finishedBooks: "Buku yang selesai dibaca",
  forgotPassword: "Lupa password?",

  ganti_foto: "Ganti Profil",

  happyReading: "Selamat membaca",
  hapus_download: "Hapus Download",
  home: "Beranda",
  hemat: "Hemat",

  ingatkan: "Ingatkan saya pada pukul..",
  invalidEmail: "Email tidak valid",

  jam: "Jam",

  kategori: "Kategori",
  kilasEmpty: "Daftar kilas kosong",
  kilasEmptyDesc:
    "Sepertinya kilas buku ini masih kosong, kamu bisa coba lirik buku lain dulu.",
  kirim: "Kirim",
  komentar: "Komentar",
  kualitas: "Kualitas Audio",
  kualitas_video: "Kualitas Video",
  kualitas_download: "Kualitas Download",
  kecepatan: "Kecepatan ",
  kecepatan_video: "Kecepatan Video",
  kecepatan_audio: "Kecepatan Audio",
  keuntungan: "Keuntungan yang didapat dengan upgrade ke premium adalah:",
  kilas_buku: "30+ Kilas Buku baru setiap bulannya!",

  lalu: " lalu",
  lastReadClue: "Eksplor kilas buku terpopuler",
  lebih_banyak: "Lihat Lebih Banyak",
  lebih_sedikit: "Lihat Lebih Sedikit",
  library: "Bukuku",
  lihat_semua: "Lihat Semua",
  listen: "Dengar",
  login: "Masuk!",
  loginHere: "Login di sini",
  langganan_sekaarang: "Langganan sekarang",
  lagi_bokek: "Lagi bokek",

  mark: "Tandai",
  marked: "Berhasil ditandai",
  markFailed: "Gagal ditandai",
  mostRead: "Paling banyak dibaca",
  menit: "Menit",
  mode_gelap: "Mode Gelap",
  masa_Account: "Masa Berlaku Premium",
  mode_offline: "Mode Offline",
  myFavorite: "Buku Favoritku",
  membuka_semua:
    "Membuka semua format ringkasan buku, mulai dari: Audio & Video.",

  name: "Nama",
  notif: "Notifikasi",
  nameCantBeEmpty: "Nama tidak boleh kosong",
  nameMinChar: "Nama minimal berisi 3 karakter",
  namePlaceholder: "Isi nama disini ...",
  newRelease: "Baru rilis",
  newSearch: "Pencarian terbaru",
  noBook: "Buku ga ditemukan!",
  notif_sistem: "Notifikasi Sistem",
  notif_promo: "Notifikasi Promo",
  notification: "Notifikasi",
  notif_empty: "Notifikasi kosong!",

  onBoard_1: "Males baca buku? Baca SekilasAja!",
  onBoard_2: "Membaca adalah habit orang sukses!",
  onBoard_3: "Udah nyerah sebelum membaca.",
  onBoard_4: "Belajar dimanapun dan kapanpun!",
  other: "kesalahan lain",

  passwordCantBeEmpty: "Password tidak boleh kosong",
  passwordDontMatch: "Password tidak sama",
  passwordInvalid: "Password tidak cocok",
  passwordMinChar: "Password minimal berisi 6 karakter",
  passwordPlaceholder: "Isi password disini ...",
  policy: "Kebijakan Privasi",
  preferensi_Account: "Preferensi",
  premium_Account: "Premium",
  pilih_bahasa: "Pilih bahasa yang kamu mengerti.",
  putar: "Putar Otomatis",
  password_minimal: "Password minimal harus berisi 8 karakter.",
  password_lama: "Password Lama",
  password_baru: "Password Baru",
  password_konfir: "Konfirmasi Password",
  password_lama_kosong: "Password lama kosong",
  password_tidak_sama: "Password tidak sama",
  permission: "Kamera tidak memiliki izin",
  pengingat: "Pengingat Harian",
  promo_voucher: "Promo & Voucher",
  password: "Password",
  publikasi: "Negara publikasi : ",
  penulis: "Penulis",
  pembaca: " pembaca",
  promo_empty: "Promo kosong!",
  pursueRead: "di dunia sekarang!",
  pilih_paket: "Pilih Paket",
  pilih_paket_premium: "Pilih paket premium yang sesuai untuk kamu!",
  pilihan_paket: "Ada 2 paket yang paling banyak dipilih oleh para pembaca. ⬇",
  pembayaran_langsung: "*Pembayaran langsung ",

  repasswordPlaceholder: "Konfirmasi password disini ...",
  recommendedBook: "Rekomendasi buku",
  regist: "Daftar!",
  registHere: "Daftar di sini.",
  rp: "Rp ",

  searchEmpty: "Saat ini kamu tidak memiliki pencarian terbaru",
  seeAll: "Lihat semua",
  share: "Bagikan",
  sub_onBoard_1:
    "Solusi buat kamu yang malas baca buku, tapi kepo pengen tau isinya.",

  sub_onBoard_2: "Banyak orang sukses menyisihkan waktuuntuk membaca buku. ",
  sub_onBoard_3:
    "Banyak orang udah males duluan kalo liat buku yang panjang...",
  sub_onBoard_4:
    "Kamu dapat belajar dan membaca segala hal dalam satu aplikasi!",
  segera: "SEGERA!",
  success: "SUCCESS",

  tableOfContent: "Daftar Isi",
  terms: "Ketentuan Layanan",
  trendingBook: "Trending buku",
  title_Account: "Pengaturan",
  tipeAkun_Account: "Tipe Akun",
  text_mode_offline:
    "Saat koneksimu buruk atau gak ada internet, kamu masih bisa menggunakan aplikasi dengan memilih mode offline.",
  text_notif: "Sesuaikan notifikasi.",
  text_putar: "Dengarkan ringkasan buku berikutnya secara otomatis.",
  text_kualitas:
    "Sesuaikan kualitas audio agar tetap mendengarkan dengan nyaman.",
  text_putar_video: "Tonton ringkasan buku berikutnya secara otomatis.",
  text_kualitas_video:
    "Sesuaikan kualitas video agar tetap menonton dengan nyaman.",
  text_kualitas_download:
    "Tentukan kualitas download ringkasan buku, untuk membuka ketika offline.",
  text_hapus_download: "Hapus semua ringkasan buku yang telah didownload.",
  text_btn_hapus: "Hapus",
  tentang: "Tentang",
  tentang_kami: "Tentang Kami",
  text_tentang:
    "Kepo sama kita? Yuk, liat yang ada dibelakang layar SekilasAja!",
  textSosmed: "Follow Sosial Media Kami",
  tgl_release: "Tanggal Rilis",
  tidak_ada_notif: "Tidak ada notifikasi  untuk saat ini.",
  tidak_ada_promo: "Tidak ada promo  untuk saat ini.",
  text_pengingat: "Kamu akan diingatkan setiap hari.",
  text_promo: "Kamu akan diberitahu setiap ada promo diskon atau voucher.",
  tonton: "Tonton",
  tentang_buku: "Tentang Buku",

  ulasan: "Ulasan",
  ulasan_dari: "Ulasan dari ",

  video: "Video",
  video_Account: "Pengaturan Video",
  video_putar: "Putar Otomatis",

  watch: "Tonton",
  weekNewCollection: "Kilas Baru minggu ini!",
  wib: "WIB",

  x: "x",

  yakin_keluar: "Yakin ingin keluar?",
  yuk_upgrade: "Yuk, upgrade dulu ke premium!",

  zona: "Zona",
};
