const SET_BOOK_RECOMENDED = "SET_BOOK_RECOMENDED";
const SET_MOST_READ_BOOK = "SET_MOST_READ_BOOK";
const SET_LIST_CATEGORY = "SET_LIST_CATEGORY";
const SET_DURATION_AUDIO = "SET_DURATION_AUDIO";

export {
  SET_BOOK_RECOMENDED,
  SET_MOST_READ_BOOK,
  SET_LIST_CATEGORY,
  SET_DURATION_AUDIO
};
