const SET_PROGRESS_VIDEO = "SET_PROGRESS_VIDEO";
const SET_VIDEO_BOOK = "SET_VIDEO_BOOK";
const PROGRESS_VIDEO = "PROGRESS_VIDEO";
const SET_DISPLAY_VIDEO = "SET_DISPLAY_VIDEO";
const CLOSE_FLOATING_VIDEO = "CLOSE_FLOATING_VIDEO";
export {
  SET_PROGRESS_VIDEO,
  PROGRESS_VIDEO,
  SET_VIDEO_BOOK,
  SET_DISPLAY_VIDEO,
  CLOSE_FLOATING_VIDEO
};
