const SET_PROGRESS_AUDIO = "SET_PROGRESS_AUDIO";
const SET_AUDIO_BOOK = "SET_AUDIO_BOOK";
const PROGRESS_AUDIO = "PROGRESS_AUDIO";
const SET_DISPLAY_AUDIO = "SET_DISPLAY_AUDIO";
const CLOSE_FLOATING_MEDIA = "CLOSE_FLOATING_MEDIA";
export {
  SET_PROGRESS_AUDIO,
  PROGRESS_AUDIO,
  SET_AUDIO_BOOK,
  SET_DISPLAY_AUDIO,
  CLOSE_FLOATING_MEDIA
};
