const SET_PROGRESS_MENTORING = "SET_PROGRESS_MENTORING";
const SET_VIDEO_MENTORING = "SET_VIDEO_MENTORING";
const PROGRESS_MENTORING = "PROGRESS_MENTORING";
const SET_DISPLAY_MENTORING = "SET_DISPLAY_MENTORING";
const CLOSE_FLOATING_MENTORING = "CLOSE_FLOATING_MENTORING";
export {
  SET_PROGRESS_MENTORING,
  PROGRESS_MENTORING,
  SET_VIDEO_MENTORING,
  SET_DISPLAY_MENTORING,
  CLOSE_FLOATING_MENTORING
};
