const SAVE = "SAVE";
const CLEAR = "CLEAR";
const OPEN_BOTTOM_TAB = "OPEN_BOTTOM_TAB";
const CLOSE_BOTTOM_TAB = "CLOSE_BOTTOM_TAB";

const TOGGLE_BOTTOM_TAB = "TOGGLE_BOTTOM_TAB";

export { SAVE, CLEAR, TOGGLE_BOTTOM_TAB, OPEN_BOTTOM_TAB, CLOSE_BOTTOM_TAB };
