const FETCH_NOTIF_PROMO = "FETCH_NOTIF_PROMO";
const FETCH_NOTIF_INBOX = "FETCH_NOTIF_INBOX";
const LOAD_FETCH_NOTIF = "LOAD_FETCH_NOTIF";
export { FETCH_NOTIF_PROMO, LOAD_FETCH_NOTIF, FETCH_NOTIF_INBOX };
